image: node:20

stages:
    - install
    - build
    - static_analysis
    - test
    - deploy

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == "main"
        - if: $CI_COMMIT_BRANCH

cache:
    paths:
        - node_modules/

variables:
    NODE_ENV: production

before_script:
    - npm ci
    - echo "[INFO] Starting pipeline..."

install:
    stage: install
    script:
        - npx prisma generate

build:
    stage:
        build
    script:
        - echo "[INFO] Start building project..."
        - if [ -z "$NEXT_PUBLIC_TMDB_API_KEY" ];
            then echo "[TEST] API key is not set...";
            else echo "[TEST] API key is set...";
            fi
        - npm run build

typecheck:
    stage: static_analysis
    script:
        - npm run typecheck

static_analysis:
    stage:
        static_analysis
    script:
        - npm run lint
    allow_failure: true



test:
    stage:
        test
    script:
        - npm test -- --coverage
    coverage: '/All files.*\s+(\d+.\d+)%/'

deploy:
    stage:
        deploy
    script:
        - echo "[MOCK] This is a mock deployment!"


